files:
  # menu music
  menu_music:
    loop: true
    src: "audio/Navidson.ogg"
  # drones - these are our background tracks and should be played
  # with `music play <name>`
  crisis:
    loop: true
    src: "audio/drones/Crisis.ogg"
  garden:
    loop: true
    src: "audio/drones/Garden.ogg"
  nobility:
    loop: true
    src: "audio/drones/Nobility.ogg"
  military:
    loop: true
    src: "audio/drones/Military.ogg"
  merchants:
    loop: true
    src: "audio/drones/Merchants.ogg"
  civilian:
    loop: true
    src: "audio/drones/Civilians.ogg"
  end_pos:
    loop: true
    src: "audio/Navidson.ogg"
  end_neg:
    loop: true
    src: "audio/drones/EndNeg.ogg"
  # motifs - these are character motifs, designed to be played the
  # first time a character appears in a scene, these are played with
  # `sound play <soundname>`.
  # make sure the right faction drone is playing or this may sound
  # dissonant as fuck!
  motif_intrigue_c:
    loop: false
    src: "audio/misc/Intrigue_C.ogg"
  motif_intrigue_e:
    loop: false
    src: "audio/misc/Intrigue_E.ogg"
  motif_executor:
    loop: false
    src: "audio/motifs/Executor.ogg"
  motif_alun:
    loop: false
    src: "audio/motifs/FeebleLord.ogg"
  motif_cerys:
    loop: false
    src: "audio/motifs/SchemingLady.ogg"
  motif_karl:
    loop: false
    src: "audio/motifs/Bartender.ogg"
  motif_delilah:
    loop: false
    src: "audio/motifs/BusinessSuit.ogg"
  motif_isaiah:
    loop: false
    src: "audio/motifs/FolkHero.ogg"
  motif_jac:
    loop: false
    src: "audio/motifs/Officer.ogg"
  motif_dod:
    loop: false
    src: "audio/motifs/ReluctantIcon.ogg"
  motif_gloria:
    loop: false
    src: "audio/motifs/EagerOrganizer.ogg"
  # misc shit
  ui-click:
    loop: false
    src: audio/misc/click.wav
    volume: 0.5
options:
  defaultMusic: menu_music
  volume: 0.5
  musicFadeInTime: 0.2
  musicFadeInDelay: 0.0
  musicFadeOutTime: 0.2
audioTriggers:
  onButtonClicked: ui-click
  onPressStart: ui-click
  onPlayerAnswered: ui-click
