allowChoosingFont: true
fontSets:
  default:
    header:
      name: Bebas Neue
      fontFamily: '"Bebas Neue", sans-serif'
      files: ["fonts/Bebas_Neue/BebasNeue-Regular.ttf"]
    body:
      name: "Cossette Titre"
      fontFamily: '"Cossette Titre", sans-serif'
      files:
        - file: "fonts/Cossette_Titre/CossetteTitre-Regular.ttf"
          options: {}
        - file: "fonts/Cossette_Titre/CossetteTitre-Regular.ttf"
          options:
            style: italic
